//
//  sptFileNames.h
//  Demo
//
//  Created by Apple on 3/23/14.
//
//

#ifndef __Demo__sptFileNames__
#define __Demo__sptFileNames__

#include <iostream>

//
//  sptFileNames.cpp
//  Demo
//
//  Created by Apple on 3/23/14.
//
//


#include "cocos2d.h"
#include <map>
#include <string>
#include <set>
using std::string;
using std::set;
using std::map;

#include "rapidxml.hpp"
#include "rapidxml_utils.hpp"
#include "rapidxml_print.hpp"
//#include "rapidxml_iterators.hpp"

using namespace rapidxml;


using namespace cocos2d;

enum SPT_FILENAMES{
    addHartButton = 0,
    arrow_0up,
    arrow_1down,
    arrow_2right_up,
    arrow_3left_down,
    arrow_4right_down,
    arrow_5left_up,
    background_set,
    big_particle,
    blackHex,
    bonus_money_1,
    bonus_money_2,
    clearTarget_2,
    clearTarget_3,
    clearTarget_4,
    clearTarget_icon1,
    clearTarget_icon2,
    clearTarget_icon3,
    clearTarget_line,
    clearTarget_text3,
    clearTarget_title,
    coinDol_00,
    coinDol_01,
    coinDol_02,
    coinDol_03,
    coinDol_04,
    coinDol_05,
    coinDol_06,
    coinDol_07,
    coinEuro_00,
    coinEuro_01,
    coinEuro_02,
    coinEuro_03,
    coinEuro_04,
    coinEuro_05,
    coinEuro_06,
    coinEuro_07,
    coinGen_00,
    coinGen_01,
    coinGen_02,
    coinGen_03,
    coinGen_04,
    coinGen_05,
    coinGen_06,
    coinGen_07,
    coinYen_00,
    coinYen_01,
    coinYen_02,
    coinYen_03,
    coinYen_04,
    coinYen_05,
    coinYen_06,
    coinYen_07,
    config,
    dateFont,
    dol_0,
    dol_1,
    dol_2,
    dol_3,
    dol_4,
    dol_5,
    dol_6,
    dynamiteFont,
    dynamite_1_yellow,
    dynamite_2_blue,
    dynamite_3_green,
    dynamite_4_red,
    effect_flip,
    euro_0,
    euro_1,
    euro_2,
    euro_3,
    euro_4,
    euro_5,
    euro_6,
    explosion,
    fence1_1,
    fence1_2,
    fence1_3,
    fence1_4,
    fence1_5,
    fence1_6,
    fence1_7,
    fence2_1,
    fence2_2,
    fence2_3,
    fence2_4,
    fence2_5,
    fence2_6,
    fence2_7,
    fire_dol_0,
    fire_dol_1,
    fire_dol_2,
    fire_dol_3,
    fire_euro_0,
    fire_euro_1,
    fire_euro_2,
    fire_euro_3,
    fire_gen_0,
    fire_gen_1,
    fire_gen_2,
    fire_gen_3,
    fire_yen_0,
    fire_yen_1,
    fire_yen_2,
    fire_yen_3,
    flip_blue,
    flip_orange,
    flip_txt,
    gameClear_1,
    gameClear_2,
    gauge_on_center_4x18,
    gauge_on_center_lighten_4x18,
    gauge_on_left,
    gauge_on_left_lighten,
    gauge_shutter,
    gauge_star_1,
    gauge_star_2,
    gen_0,
    gen_1,
    gen_2,
    gen_3,
    gen_4,
    gen_5,
    gen_6,
    hero_yen_smile,
    hexBase,
    hex_0,
    hex_1,
    hex_2,
    hex_3,
    hex_4,
    item1,
    item2,
    item3,
    itemFont2,
    item_icon_10001,
    item_icon_10002,
    item_icon_10003,
    item_icon_10004,
    key_,
    light_0,
    light_1,
    light_color_0,
    light_color_1,
    light_color_2,
    light_color_3,
    line_bg_1,
    line_bg_2,
    line_bg_3,
    line_bg_4,
    line_sign_bg_1,
    line_sign_bg_2,
    line_sign_bg_3,
    line_sign_bg_4,
    line_top_1,
    line_top_2,
    line_top_3,
    line_top_4,
    lock_1,
    lock_2,
    miniStar_0001,
    miniStar_0002,
    miniStar_0003,
    miniStar_0004,
    miniStar_0005,
    miniStar_0006,
    miniStar_0007,
    miniStar_0008,
    miniStar_0009,
    miniStar_0010,
    miniStar_0011,
    miniStar_0012,
    miniStar_0013,
    miniStar_0014,
    miniStar_0015,
    miniStar_0016,
    miniStar_0017,
    miniStar_0018,
    miniStar_0019,
    miniStar_0020,
    miniStar_0021,
    miniStar_0022,
    miniStar_0023,
    miniStar_0024,
    miniStar_0025,
    paperDol_00,
    paperDol_01,
    paperDol_02,
    paperDol_03,
    paperDol_04,
    paperDol_05,
    paperDol_06,
    paperDol_07,
    paperDol_08,
    paperDol_09,
    paperDol_10,
    paperDol_11,
    paperDol_12,
    paperDol_13,
    paperDol_14,
    paperEuro_00,
    paperEuro_01,
    paperEuro_02,
    paperEuro_03,
    paperEuro_04,
    paperEuro_05,
    paperEuro_06,
    paperEuro_07,
    paperEuro_08,
    paperEuro_09,
    paperEuro_10,
    paperEuro_11,
    paperEuro_12,
    paperEuro_13,
    paperEuro_14,
    paperGen_00,
    paperGen_01,
    paperGen_02,
    paperGen_03,
    paperGen_04,
    paperGen_05,
    paperGen_06,
    paperGen_07,
    paperGen_08,
    paperGen_09,
    paperGen_10,
    paperGen_11,
    paperGen_12,
    paperGen_13,
    paperGen_14,
    paperYen_00,
    paperYen_01,
    paperYen_02,
    paperYen_03,
    paperYen_04,
    paperYen_05,
    paperYen_06,
    paperYen_07,
    paperYen_08,
    paperYen_09,
    paperYen_10,
    paperYen_11,
    paperYen_12,
    paperYen_13,
    paperYen_14,
    pushBtn_base_off,
    pushBtn_base_on,
    radialStar00,
    radialStar01,
    radialStar02,
    radialStar03,
    radialStar04,
    radialStar05,
    radialStar06,
    radialStar07,
    radialStar08,
    radialStar09,
    radialStar10,
    radialStar11,
    radialStar12,
    radialStar13,
    radialStar14,
    radialStar15,
    radialStar16,
    radialStar17,
    radialStar18,
    radialStar19,
    radialStar20,
    radialStar21,
    radialStar22,
    radialStar23,
    radialStar24,
    radialStar25,
    radialStar26,
    radialStar27,
    radialStar28,
    radialStar29,
    radialStar30,
    radialStar31,
    radialStar32,
    radialStar33,
    radialStar34,
    radialStar35,
    radialStar36,
    radialStar37,
    radialStar38,
    radialStar39,
    radialStar40,
    radialStar41,
    radialStar42,
    radialStar43,
    radialStar44,
    radialStar45,
    radialStar46,
    radialStar47,
    radialStar48,
    radialStar49,
    radialStar50,
    radialStar51,
    radialStar52,
    radialStar53,
    scoreFont,
    score_bar_light,
    shuffle_arrow_1,
    shuffle_arrow_2,
    shuffle_main,
    shuffle_sub,
    shutter_,
    smoke_00,
    smoke_01,
    smoke_02,
    smoke_03,
    smoke_04,
    smoke_05,
    smoke_06,
    smoke_07,
    smoke_08,
    smoke_09,
    smoke_10,
    smoke_11,
    smoke_12,
    smoke_13,
    smoke_14,
    stoneLv2_crash_l,
    stoneLv2_crash_s,
    stone_crash_l,
    stone_crash_s,
    stone_level1,
    stone_level2,
    stone_level2_2,
    timeUp_main,
    timeUp_sub,
    turnEnd_main,
    turnEnd_sub,
    turnFont,
    turn_txt0,
    turn_txt1,
    tutorial_finger,
    tutorial_stage01_text01,
    tutorial_stage01_text02,
    tutorial_stage01_text03,
    tutorial_stage01_text04,
    tutorial_stage02_text01,
    tutorial_stage02_text02,
    tutorial_stage03_text01,
    tutorial_stage04_text01,
    tutorial_stage05_text01,
    tutorial_stage05_text02,
    tutorial_yukichi_01_normal,
    tutorial_yukichi_02_smile,
    tutorial_yukichi_03_happy,
    tutorial_yukichi_04_surprise,
    tutorial_yukichi_05_sad,
    window_common_base,
    yen_0,
    yen_1,
    yen_2,
    yen_3,
    yen_4,
    yen_5,
    yen_6,
    zannen_1,
    
};


extern const char *sptFileNames[];


struct SubTexture{
    std::string name;
//    union {
//        CCRect stPos;
//        struct {
//            int x, y;
//            int width, height;
//        } rt;
//    };
    int x, y;
    int width, height;
    int pivotX, pivotY;
    //CCRect      rt;
};


extern std::map<int, SubTexture*> gSubTexture;

std::map<int, SubTexture*> getXmlConfig(const char *str);
void releaseXmlConfigData();



#endif /* defined(__Demo__sptFileNames__) */
